//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRM_FAST
{
    using System;
    using System.Collections.Generic;
    
    public partial class AUTORIZZAZIONI
    {
        public int idOfferta { get; set; }
        public string tipoRichiesta { get; set; }
        public string richiestaA { get; set; }
        public Nullable<System.DateTime> dataRichiesta { get; set; }
        public string AutorizzataDa { get; set; }
        public Nullable<System.DateTime> dataEsito { get; set; }
        public Nullable<int> esito { get; set; }
        public string xmlDetails { get; set; }
    
        public virtual Offerte Offerte { get; set; }
    }
}
