//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRM_FAST
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cars
    {
        public int IDCars { get; set; }
        public string Packet { get; set; }
        public string PacketVersion { get; set; }
        public string Process { get; set; }
        public Nullable<int> DutyLoad { get; set; }
        public Nullable<short> AccessNum { get; set; }
        public string DoorType { get; set; }
        public Nullable<int> LL { get; set; }
        public Nullable<int> BB { get; set; }
        public Nullable<int> DD { get; set; }
        public Nullable<int> WWmin { get; set; }
        public Nullable<int> WWmax { get; set; }
        public Nullable<int> Gmin { get; set; }
        public Nullable<int> Gmax { get; set; }
        public Nullable<int> WD { get; set; }
        public Nullable<int> WDmax { get; set; }
        public Nullable<int> CAR_CX { get; set; }
        public Nullable<int> CAR_CXmin { get; set; }
        public Nullable<int> CAR_CXmax { get; set; }
        public Nullable<short> Persons { get; set; }
        public short CTWSG { get; set; }
        public string Speed { get; set; }
        public Nullable<int> CW { get; set; }
        public Nullable<int> CW1 { get; set; }
    }
}
