//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRM_FAST
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cars_New
    {
        public int idCars { get; set; }
        public string Packet { get; set; }
        public string PacketVersion { get; set; }
        public string Process { get; set; }
        public Nullable<int> Load { get; set; }
        public string Speed { get; set; }
        public Nullable<short> Entrance { get; set; }
        public Nullable<int> BB { get; set; }
        public Nullable<int> DD { get; set; }
        public string CTWSG { get; set; }
        public Nullable<short> Persons { get; set; }
        public string Door_Design { get; set; }
        public Nullable<short> Door_Model { get; set; }
        public Nullable<int> LL { get; set; }
        public Nullable<int> Gmin { get; set; }
        public Nullable<int> Gmax { get; set; }
        public Nullable<int> WWmin { get; set; }
        public Nullable<int> WWmax { get; set; }
        public Nullable<int> WDmin { get; set; }
        public Nullable<int> WDmax { get; set; }
        public Nullable<int> DO { get; set; }
        public Nullable<int> CXmin { get; set; }
        public Nullable<int> CXmax { get; set; }
        public string Machine_type { get; set; }
        public string Guiderails_type { get; set; }
        public string EN81_1 { get; set; }
        public string EN81_70 { get; set; }
        public string EN81_72 { get; set; }
        public string Pubel_92 { get; set; }
        public string EN81_71 { get; set; }
        public string Pubel_2003 { get; set; }
        public Nullable<int> CW { get; set; }
        public Nullable<int> CW1 { get; set; }
        public string DoorType { get; set; }
    }
}
