//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRM_FAST
{
    using System;
    using System.Collections.Generic;
    
    public partial class CategoryLog
    {
        public int CategoryLogID { get; set; }
        public int CategoryID { get; set; }
        public int LogID { get; set; }
    
        public virtual Category Category { get; set; }
        public virtual Log Log { get; set; }
    }
}
