//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRM_FAST
{
    using System;
    using System.Collections.Generic;
    
    public partial class Configuratori
    {
        public int IDConfiguratori { get; set; }
        public string NomePacchetto { get; set; }
        public string Template { get; set; }
        public string Note { get; set; }
        public Nullable<System.DateTime> DataInizioValidita { get; set; }
        public Nullable<System.DateTime> DataFineValidita { get; set; }
    }
}
