//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRM_FAST
{
    using System;
    using System.Collections.Generic;
    
    public partial class DAT_SF_opportunities
    {
        public string ID { get; set; }
        public string ACCOUNTID { get; set; }
        public string STAGENAME { get; set; }
        public string ISCLOSED { get; set; }
        public string ISWON { get; set; }
        public string BUSINESS_TYPE { get; set; }
        public string SALES_ORGANIZATION__CODE { get; set; }
        public string EsportatoSAP { get; set; }
        public Nullable<float> AMOUNT { get; set; }
        public string SF_OwnerID { get; set; }
        public string Opportunity_Code { get; set; }
        public string Offerta_DataPrevistaChiusura { get; set; }
        public string Offerta_ProbabilitaAggiudicazione { get; set; }
        public string Party_RagioneSociale { get; set; }
        public string Party_Indirizzo { get; set; }
        public string Party_IDParty { get; set; }
        public string Party_CITY { get; set; }
        public string Party_POSTAL_CODE { get; set; }
        public string Party_REGION { get; set; }
        public string Party_PHONE { get; set; }
        public string Party_FAX { get; set; }
        public string Description { get; set; }
        public Nullable<System.DateTime> UpdateDtime { get; set; }
        public string Opportunity_Category { get; set; }
        public string sold_to_Party_RagioneSociale { get; set; }
        public string sold_to_Party_Indirizzo { get; set; }
        public string sold_to_Party_IDParty { get; set; }
        public string sold_to_Party_CITY { get; set; }
        public string sold_to_Party_POSTAL_CODE { get; set; }
        public string sold_to_Party_REGION { get; set; }
        public string sold_to_Party_PHONE { get; set; }
        public string sold_to_Party_FAX { get; set; }
    }
}
