//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRM_FAST
{
    using System;
    using System.Collections.Generic;
    
    public partial class DAT_SALES_OFFICE
    {
        public string sales_office_code { get; set; }
        public string sales_office_desc { get; set; }
        public string sales_office_area { get; set; }
        public string sales_office_translation { get; set; }
        public string sales_office_ubicazione { get; set; }
    }
}
