//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRM_FAST
{
    using System;
    using System.Collections.Generic;
    
    public partial class DAT_SALES_GROUPS
    {
        public string Sales_group_code { get; set; }
        public string Sales_group_desc { get; set; }
        public Nullable<System.DateTime> Extr_date { get; set; }
        public Nullable<System.DateTime> Dt_upd_tab { get; set; }
    }
}
