//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRM_FAST
{
    using System;
    using System.Collections.Generic;
    
    public partial class dbo_SAPCaratteristiche
    {
        public string NCSAP { get; set; }
        public string CODPACCHETTO { get; set; }
        public string XPATH { get; set; }
        public string TLOOKUPGROUP { get; set; }
        public int id { get; set; }
    }
}
