//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRM_FAST
{
    using System;
    using System.Collections.Generic;
    
    public partial class dbRef_Listino_Storico
    {
        public int IdPubblicazione { get; set; }
        public System.DateTime DataPubblicazione { get; set; }
        public string KaiPubblicazione { get; set; }
        public string IDPrezzo { get; set; }
        public string IDNamespace { get; set; }
        public string ExcelCella { get; set; }
        public Nullable<double> Valore { get; set; }
        public Nullable<float> Valore_vecchio { get; set; }
        public string RefVarType { get; set; }
        public string Note { get; set; }
        public string NoteTecniche { get; set; }
        public Nullable<System.DateTime> DataModifica { get; set; }
        public Nullable<short> Famiglia { get; set; }
        public string Operatore { get; set; }
    }
}
