//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRM_FAST
{
    using System;
    using System.Collections.Generic;
    
    public partial class Depliants_Trace_Elenco
    {
        public int id { get; set; }
        public System.DateTime data { get; set; }
        public string Richiedente_Kai { get; set; }
        public string numeroRichiesta { get; set; }
        public int Status { get; set; }
    }
}
