//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRM_FAST
{
    using System;
    using System.Collections.Generic;
    
    public partial class Depliants_Trace
    {
        public int id { get; set; }
        public int Depliant_Id { get; set; }
        public int Qta { get; set; }
        public System.DateTime dataRichiesta { get; set; }
        public Nullable<int> qtaElargita { get; set; }
        public Nullable<short> status { get; set; }
        public Nullable<int> id_Richiesta { get; set; }
    }
}
