//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRM_FAST
{
    using System;
    using System.Collections.Generic;
    
    public partial class Depliants
    {
        public int id { get; set; }
        public string Codice { get; set; }
        public string Revisione { get; set; }
        public string Descrizione { get; set; }
        public string Thumbnail { get; set; }
        public string Immagine { get; set; }
        public Nullable<int> Ordinamento { get; set; }
        public Nullable<short> FuoriCorso { get; set; }
    }
}
