//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRM_FAST
{
    using System;
    using System.Collections.Generic;
    
    public partial class DTSEBTasks
    {
        public int idTask { get; set; }
        public int idLavoro { get; set; }
        public int idOfferta { get; set; }
        public string equipment_number { get; set; }
        public string kai_richiedente { get; set; }
        public string nome_richiedente { get; set; }
        public string descrizione { get; set; }
        public System.DateTime data_richiesta { get; set; }
        public Nullable<System.DateTime> data_completamento { get; set; }
        public string kai_esecutore { get; set; }
        public string nome_esecutore { get; set; }
        public Nullable<short> annullato { get; set; }
        public string commenti { get; set; }
    }
}
