//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRM_FAST
{
    using System;
    using System.Collections.Generic;
    
    public partial class FastPorte_Lavori
    {
        public string CodiceFAST { get; set; }
        public string Titolo { get; set; }
        public string Descrizione { get; set; }
        public string CodiceSAP { get; set; }
        public Nullable<System.DateTime> DataFineValidita { get; set; }
        public string L1 { get; set; }
        public string L2 { get; set; }
        public string L3 { get; set; }
        public string L4 { get; set; }
        public Nullable<double> materiali { get; set; }
        public Nullable<double> ore { get; set; }
        public string Documento { get; set; }
        public string visibileDa { get; set; }
        public string categoria { get; set; }
    }
}
