//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRM_FAST
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class FASTEntities : DbContext
    {
        public FASTEntities()
            : base("name=FASTEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<DAT_SF_owners> DAT_SF_owners { get; set; }
        public virtual DbSet<DAT_SF_opportunities> DAT_SF_opportunities { get; set; }
        public virtual DbSet<Venditori> Venditori { get; set; }
        public virtual DbSet<Aree> Aree { get; set; }
        public virtual DbSet<Cars> Cars { get; set; }
        public virtual DbSet<CategorieLavori> CategorieLavori { get; set; }
        public virtual DbSet<Category> Category { get; set; }
        public virtual DbSet<CategoryLog> CategoryLog { get; set; }
        public virtual DbSet<CFG_AccessiCabina> CFG_AccessiCabina { get; set; }
        public virtual DbSet<CFG_AccessoriSiNo> CFG_AccessoriSiNo { get; set; }
        public virtual DbSet<CFG_Anello> CFG_Anello { get; set; }
        public virtual DbSet<CFG_Azionamento> CFG_Azionamento { get; set; }
        public virtual DbSet<CFG_Configuratori> CFG_Configuratori { get; set; }
        public virtual DbSet<CFG_Corrente> CFG_Corrente { get; set; }
        public virtual DbSet<CFG_Fermate> CFG_Fermate { get; set; }
        public virtual DbSet<CFG_Listino_Accessori> CFG_Listino_Accessori { get; set; }
        public virtual DbSet<CFG_Listino_BasiQuadroDrive> CFG_Listino_BasiQuadroDrive { get; set; }
        public virtual DbSet<CFG_Listino_Prezzi> CFG_Listino_Prezzi { get; set; }
        public virtual DbSet<CFG_OffertaQuadro> CFG_OffertaQuadro { get; set; }
        public virtual DbSet<CFG_Portata> CFG_Portata { get; set; }
        public virtual DbSet<CFG_Quadro> CFG_Quadro { get; set; }
        public virtual DbSet<CFG_RES40_ListaCampi> CFG_RES40_ListaCampi { get; set; }
        public virtual DbSet<CFG_Schede> CFG_Schede { get; set; }
        public virtual DbSet<CFG_ServiziLatoC> CFG_ServiziLatoC { get; set; }
        public virtual DbSet<CFG_Tensione> CFG_Tensione { get; set; }
        public virtual DbSet<CFG_TensioneFreno> CFG_TensioneFreno { get; set; }
        public virtual DbSet<CFG_Velocita> CFG_Velocita { get; set; }
        public virtual DbSet<Configuratori> Configuratori { get; set; }
        public virtual DbSet<CostiTrasporto> CostiTrasporto { get; set; }
        public virtual DbSet<dbRef_Dettaglio> dbRef_Dettaglio { get; set; }
        public virtual DbSet<dbRef_Dettaglio_Storico> dbRef_Dettaglio_Storico { get; set; }
        public virtual DbSet<dbRef_Listino> dbRef_Listino { get; set; }
        public virtual DbSet<dbRef_Listino_Storico> dbRef_Listino_Storico { get; set; }
        public virtual DbSet<Depliants> Depliants { get; set; }
        public virtual DbSet<Depliants_Trace> Depliants_Trace { get; set; }
        public virtual DbSet<Depliants_Trace_Elenco> Depliants_Trace_Elenco { get; set; }
        public virtual DbSet<DepliantsStatusElenco> DepliantsStatusElenco { get; set; }
        public virtual DbSet<DepliantsStatusRichieste> DepliantsStatusRichieste { get; set; }
        public virtual DbSet<DescrizioniLavori> DescrizioniLavori { get; set; }
        public virtual DbSet<Documenti> Documenti { get; set; }
        public virtual DbSet<DTSEBTasks> DTSEBTasks { get; set; }
        public virtual DbSet<EDMSData> EDMSData { get; set; }
        public virtual DbSet<extractKIT> extractKIT { get; set; }
        public virtual DbSet<fastLog> fastLog { get; set; }
        public virtual DbSet<idGenerator> idGenerator { get; set; }
        public virtual DbSet<Impianti> Impianti { get; set; }
        public virtual DbSet<ImpiantiInOfferte> ImpiantiInOfferte { get; set; }
        public virtual DbSet<LavoriACaricoCliente> LavoriACaricoCliente { get; set; }
        public virtual DbSet<LavoriInOfferte> LavoriInOfferte { get; set; }
        public virtual DbSet<LavoriNonCOdificati> LavoriNonCOdificati { get; set; }
        public virtual DbSet<Log> Log { get; set; }
        public virtual DbSet<LookupTables> LookupTables { get; set; }
        public virtual DbSet<Mail> Mail { get; set; }
        public virtual DbSet<MilestonePianoFatt> MilestonePianoFatt { get; set; }
        public virtual DbSet<ModificaOrdine> ModificaOrdine { get; set; }
        public virtual DbSet<News> News { get; set; }
        public virtual DbSet<Offerte> Offerte { get; set; }
        public virtual DbSet<OneriCompresiEsclusi> OneriCompresiEsclusi { get; set; }
        public virtual DbSet<OneriOfferte> OneriOfferte { get; set; }
        public virtual DbSet<Pacchetti> Pacchetti { get; set; }
        public virtual DbSet<Parametri> Parametri { get; set; }
        public virtual DbSet<Parties> Parties { get; set; }
        public virtual DbSet<PianoFatturazione> PianoFatturazione { get; set; }
        public virtual DbSet<Price> Price { get; set; }
        public virtual DbSet<PriceGroup> PriceGroup { get; set; }
        public virtual DbSet<PriceItem> PriceItem { get; set; }
        public virtual DbSet<Provvigioni> Provvigioni { get; set; }
        public virtual DbSet<Referenze> Referenze { get; set; }
        public virtual DbSet<ReportFinanziari> ReportFinanziari { get; set; }
        public virtual DbSet<SAPCaratteristiche> SAPCaratteristiche { get; set; }
        public virtual DbSet<TerminiDiPagamento> TerminiDiPagamento { get; set; }
        public virtual DbSet<Variabili> Variabili { get; set; }
        public virtual DbSet<VariabiliPrice> VariabiliPrice { get; set; }
        public virtual DbSet<AUTORIZZAZIONI> AUTORIZZAZIONI { get; set; }
        public virtual DbSet<Cars_FURE> Cars_FURE { get; set; }
        public virtual DbSet<Cars_New> Cars_New { get; set; }
        public virtual DbSet<CFG_Servizi> CFG_Servizi { get; set; }
        public virtual DbSet<CFG_Versioni> CFG_Versioni { get; set; }
        public virtual DbSet<DAT_SALES_GROUPS> DAT_SALES_GROUPS { get; set; }
        public virtual DbSet<DAT_SALES_OFFICE> DAT_SALES_OFFICE { get; set; }
        public virtual DbSet<DAT_SALES_ORGANIZATION> DAT_SALES_ORGANIZATION { get; set; }
        public virtual DbSet<dbo_SAPCaratteristiche> dbo_SAPCaratteristiche { get; set; }
        public virtual DbSet<dbRef_lookup_FamigliaCosto> dbRef_lookup_FamigliaCosto { get; set; }
        public virtual DbSet<dtproperties> dtproperties { get; set; }
        public virtual DbSet<FastPorte_Lavori> FastPorte_Lavori { get; set; }
        public virtual DbSet<FastScaleTappeti_Lavori> FastScaleTappeti_Lavori { get; set; }
        public virtual DbSet<LavoriCodificati> LavoriCodificati { get; set; }
        public virtual DbSet<LavoriCodificati2006> LavoriCodificati2006 { get; set; }
        public virtual DbSet<LavoriCodificati2012> LavoriCodificati2012 { get; set; }
        public virtual DbSet<LavoriCodificatiPrezzoLibero> LavoriCodificatiPrezzoLibero { get; set; }
        public virtual DbSet<PARERI> PARERI { get; set; }
        public virtual DbSet<QUOTAZIONI> QUOTAZIONI { get; set; }
        public virtual DbSet<rpt_offerte_Manutenzione> rpt_offerte_Manutenzione { get; set; }
    }
}
