//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRM_FAST
{
    using System;
    using System.Collections.Generic;
    
    public partial class ImpiantiInOfferte
    {
        public ImpiantiInOfferte()
        {
            this.LavoriInOfferte = new HashSet<LavoriInOfferte>();
        }
    
        public int IDOfferta { get; set; }
        public string equipment_number { get; set; }
        public string detLocalizzazione { get; set; }
        public string note { get; set; }
        public string ubicazioneSpecifica { get; set; }
        public Nullable<float> totRspDaJobFile { get; set; }
    
        public virtual Impianti Impianti { get; set; }
        public virtual Offerte Offerte { get; set; }
        public virtual ICollection<LavoriInOfferte> LavoriInOfferte { get; set; }
    }
}
