//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRM_FAST
{
    using System;
    using System.Collections.Generic;
    
    public partial class LavoriCodificati
    {
        public string CodiceFAST { get; set; }
        public string Titolo { get; set; }
        public Nullable<decimal> CostoMateriali { get; set; }
        public Nullable<float> Ore { get; set; }
        public Nullable<float> Efficienza { get; set; }
        public string CodiceM2 { get; set; }
        public string Documento { get; set; }
        public string ApplyToCat { get; set; }
        public string ApplyToSubCat { get; set; }
        public Nullable<int> leadTime { get; set; }
        public string CodiceSAP { get; set; }
        public string L1 { get; set; }
        public string L2 { get; set; }
        public string L3 { get; set; }
        public string L4 { get; set; }
        public string categoria { get; set; }
        public string processo { get; set; }
        public Nullable<float> cm2 { get; set; }
        public Nullable<int> revisione { get; set; }
        public Nullable<System.DateTime> dataFuoriCorso { get; set; }
        public int id { get; set; }
    }
}
