//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRM_FAST
{
    using System;
    using System.Collections.Generic;
    
    public partial class LavoriACaricoCliente
    {
        public string CodiceFast { get; set; }
        public string Titolo { get; set; }
        public string Descrizione { get; set; }
        public string ApplyToCat { get; set; }
        public string ApplyToSubCat { get; set; }
        public string Inventore { get; set; }
    }
}
