//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRM_FAST
{
    using System;
    using System.Collections.Generic;
    
    public partial class LavoriNonCOdificati
    {
        public string CodiceFast { get; set; }
        public string Titolo { get; set; }
        public string Descrizione { get; set; }
        public Nullable<float> OreManovalanza { get; set; }
        public Nullable<float> OreManodopera { get; set; }
        public Nullable<float> CostoMaterialiInterCompany { get; set; }
        public Nullable<float> CostoMaterialiIntraCompany { get; set; }
        public Nullable<float> CostoMaterialiExtraCompany { get; set; }
        public string ApplyToCat { get; set; }
        public string ApplyToSubCat { get; set; }
        public string Inventore { get; set; }
        public string categoria { get; set; }
        public Nullable<int> LeadTime { get; set; }
        public Nullable<int> VerificaStraordinaria { get; set; }
        public int id { get; set; }
    }
}
