//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRM_FAST
{
    using System;
    using System.Collections.Generic;
    
    public partial class LavoriInOfferte
    {
        public int idLavoro { get; set; }
        public int IDOfferta { get; set; }
        public string equipment_number { get; set; }
        public string tpLavoro { get; set; }
        public string CodiceFast { get; set; }
        public decimal CostoMaterialiInterCompany { get; set; }
        public decimal CostoMaterialiIntraCompany { get; set; }
        public decimal CostoMaterialiEsterni { get; set; }
        public float OreManodopera { get; set; }
        public float OreManovalanza { get; set; }
        public string xmlDetails { get; set; }
        public float Prezzo { get; set; }
        public Nullable<float> Quantita { get; set; }
        public Nullable<System.DateTime> DataRichiestaQuotazione { get; set; }
        public Nullable<System.DateTime> DataQuotazione { get; set; }
        public string CodiceSAP { get; set; }
        public Nullable<int> flgVariante { get; set; }
        public Nullable<int> LeadTime { get; set; }
        public Nullable<double> ExtraCosti { get; set; }
        public Nullable<double> ExtraOre { get; set; }
        public string categoria { get; set; }
        public string processo { get; set; }
        public Nullable<float> cm2 { get; set; }
        public Nullable<int> flgACaricoKone { get; set; }
        public Nullable<int> PrezzoLibero { get; set; }
        public Nullable<int> revisione { get; set; }
        public string Descrizione { get; set; }
        public Nullable<float> fhr { get; set; }
        public Nullable<float> CM2DiPartenza { get; set; }
        public Nullable<float> PrezzoAcq { get; set; }
        public Nullable<float> cm2Acq { get; set; }
        public string IDOrdine { get; set; }
        public Nullable<float> PrezzoMateriali { get; set; }
    
        public virtual ImpiantiInOfferte ImpiantiInOfferte { get; set; }
    }
}
