//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRM_FAST
{
    using System;
    using System.Collections.Generic;
    
    public partial class LavoriCodificatiPrezzoLibero
    {
        public string CodiceFast { get; set; }
        public string Titolo { get; set; }
        public string Descrizione { get; set; }
        public string CodiceSAP { get; set; }
        public string categoria { get; set; }
        public string processo { get; set; }
        public int leadTime { get; set; }
        public short DescrizioneModificabile { get; set; }
        public string Tipologia { get; set; }
        public Nullable<System.DateTime> DataFineValidita { get; set; }
    }
}
