//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRM_FAST
{
    using System;
    using System.Collections.Generic;
    
    public partial class LookupTables
    {
        public string tLookupGroup { get; set; }
        public string tLookupSeed { get; set; }
        public string tLookupResult { get; set; }
        public Nullable<short> sortKey { get; set; }
    }
}
