//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRM_FAST
{
    using System;
    using System.Collections.Generic;
    
    public partial class ModificaOrdine
    {
        public int IDModifica { get; set; }
        public int idOfferta { get; set; }
        public string Motivazione { get; set; }
        public System.DateTime DataInizioModifica { get; set; }
        public string IniziataDa { get; set; }
        public Nullable<double> RSPPrecedente { get; set; }
        public Nullable<double> CM2Precedente { get; set; }
        public Nullable<double> MaterialiPrecedente { get; set; }
        public Nullable<double> OrePrecedente { get; set; }
        public Nullable<System.DateTime> DataFineModifica { get; set; }
        public string FinitaDa { get; set; }
        public Nullable<double> RSPModifica { get; set; }
        public Nullable<double> RSPAttuale { get; set; }
        public Nullable<double> CM2Attuale { get; set; }
        public Nullable<double> MaterialiAttuale { get; set; }
        public Nullable<double> OreAttuale { get; set; }
    }
}
