//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRM_FAST
{
    using System;
    using System.Collections.Generic;
    
    public partial class OneriCompresiEsclusi
    {
        public int idOnere { get; set; }
        public string Descrizione { get; set; }
        public int defaultCOmpreso { get; set; }
        public int visualizzaInOfferta { get; set; }
        public string Categoria { get; set; }
        public short Sequence { get; set; }
        public string codiceSAP { get; set; }
    }
}
