//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRM_FAST
{
    using System;
    using System.Collections.Generic;
    
    public partial class OneriOfferte
    {
        public int IDOfferta { get; set; }
        public int IDOnere { get; set; }
        public short flgCompreso { get; set; }
        public Nullable<double> MaterialiIntraCompany { get; set; }
        public Nullable<double> MaterialiExtraCompany { get; set; }
        public Nullable<double> MaterialiInterCOmpany { get; set; }
        public Nullable<double> OreManovalanza { get; set; }
        public Nullable<double> OreManodopera { get; set; }
        public Nullable<short> flgMostraInOfferta { get; set; }
        public string Titolo { get; set; }
        public string Descrizione { get; set; }
    
        public virtual Offerte Offerte { get; set; }
    }
}
