//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRM_FAST
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pacchetti
    {
        public string CodiceFAST { get; set; }
        public string Descrizione { get; set; }
        public Nullable<int> leadTime { get; set; }
        public Nullable<int> flgPacchettoLocale { get; set; }
        public string applyToCat { get; set; }
        public string applyToSubCat { get; set; }
        public Nullable<int> flgVerificaStraordinaria { get; set; }
        public Nullable<float> extraMaterialiIntraCompany { get; set; }
        public Nullable<float> extraMaterialiExtraCompany { get; set; }
        public Nullable<float> extraMaterialiInterCompany { get; set; }
        public Nullable<float> extraOreManodopera { get; set; }
        public Nullable<float> moltiplicatoreMateriali { get; set; }
        public string categoria { get; set; }
        public string processo { get; set; }
        public Nullable<float> cm2 { get; set; }
        public Nullable<int> revisione { get; set; }
        public Nullable<System.DateTime> dataFuoriCorso { get; set; }
        public string tipologia { get; set; }
    }
}
