//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRM_FAST
{
    using System;
    using System.Collections.Generic;
    
    public partial class Parties
    {
        public Parties()
        {
            this.Impianti = new HashSet<Impianti>();
            this.Offerte = new HashSet<Offerte>();
        }
    
        public string IDParty { get; set; }
        public string RagioneSociale { get; set; }
        public string PrefissoIndirizzo { get; set; }
        public string Indirizzo { get; set; }
        public string Civico { get; set; }
        public string CAP { get; set; }
        public string Localita { get; set; }
        public string Paese { get; set; }
        public string Provincia { get; set; }
        public string Telefono { get; set; }
        public string Fax { get; set; }
        public string Contatto { get; set; }
        public string Email { get; set; }
        public string PartitaIVA { get; set; }
        public string CodiceFiscale { get; set; }
        public string ABI { get; set; }
        public string CAB { get; set; }
        public string numeroCC { get; set; }
        public string Classe { get; set; }
        public string Categoria { get; set; }
        public string xmlDetails { get; set; }
        public string IDVenditore { get; set; }
        public string Distretto { get; set; }
        public Nullable<System.DateTime> DataRichiestaAllineamento { get; set; }
        public Nullable<System.DateTime> DataAllineamento { get; set; }
        public string GruppoCliente { get; set; }
        public string modalitaFatturazione { get; set; }
        public string modalitaPagamento { get; set; }
        public string ivaPagamento { get; set; }
    
        public virtual ICollection<Impianti> Impianti { get; set; }
        public virtual ICollection<Offerte> Offerte { get; set; }
    }
}
