//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRM_FAST
{
    using System;
    using System.Collections.Generic;
    
    public partial class PriceGroup
    {
        public int IDPriceGroup { get; set; }
        public int IDConfiguratore { get; set; }
        public Nullable<bool> Enabled { get; set; }
        public string Descr { get; set; }
        public string Name { get; set; }
    }
}
