//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRM_FAST
{
    using System;
    using System.Collections.Generic;
    
    public partial class Provvigioni
    {
        public int id { get; set; }
        public Nullable<decimal> sconto_min { get; set; }
        public Nullable<decimal> sconto_MAX { get; set; }
        public Nullable<decimal> provvigione { get; set; }
    }
}
