//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRM_FAST
{
    using System;
    using System.Collections.Generic;
    
    public partial class Referenze
    {
        public int IDReferenza { get; set; }
        public string Template { get; set; }
        public string categoria { get; set; }
        public string MainPicture { get; set; }
        public string TRPicture { get; set; }
        public string BRPicture { get; set; }
        public string Titolo { get; set; }
        public string R1Sottotitolo { get; set; }
        public string R2Sottotitolo { get; set; }
        public string B1Titolo { get; set; }
        public string B1R1C1 { get; set; }
        public string B1R1C2 { get; set; }
        public string B1R2C1 { get; set; }
        public string B1R2C2 { get; set; }
        public string B1R3C1 { get; set; }
        public string B1R3C2 { get; set; }
        public string B1R4C1 { get; set; }
        public string B1R4C2 { get; set; }
        public string B1R5C1 { get; set; }
        public string B1R5C2 { get; set; }
        public string B1R6C1 { get; set; }
        public string B1R6C2 { get; set; }
        public string B2Titolo { get; set; }
        public string B2R1C1 { get; set; }
        public string B2R1C2 { get; set; }
        public string B2R2C1 { get; set; }
        public string B2R2C2 { get; set; }
        public string B2R3C1 { get; set; }
        public string B2R3C2 { get; set; }
        public string B2R4C1 { get; set; }
        public string B2R4C2 { get; set; }
        public string B2R5C1 { get; set; }
        public string B2R5C2 { get; set; }
        public string B2R6C1 { get; set; }
        public string B2R6C2 { get; set; }
        public string B3Titolo { get; set; }
        public string B3R1C1 { get; set; }
        public string B3R1C2 { get; set; }
        public string B3R2C1 { get; set; }
        public string B3R2C2 { get; set; }
        public string B3R3C1 { get; set; }
        public string B3R3C2 { get; set; }
        public string B3R4C1 { get; set; }
        public string B3R4C2 { get; set; }
        public string B3R5C1 { get; set; }
        public string B3R5C2 { get; set; }
        public string B3R6C1 { get; set; }
        public string B3R6C2 { get; set; }
    }
}
