//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRM_FAST
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReportFinanziari
    {
        public long Id { get; set; }
        public string NomeReport { get; set; }
        public short Livello { get; set; }
        public string Area { get; set; }
        public string Distretto { get; set; }
        public string Venditori { get; set; }
        public short Mese { get; set; }
        public short Anno { get; set; }
    }
}
