//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRM_FAST
{
    using System;
    using System.Collections.Generic;
    
    public partial class rpt_offerte_Manutenzione
    {
        public int IDOfferta { get; set; }
        public Nullable<int> IDlavoro { get; set; }
        public string IdEnte { get; set; }
        public string IdVenditore { get; set; }
        public string venditore { get; set; }
        public string NumeroOfferta { get; set; }
        public string SoldTo_Party_code { get; set; }
        public string SoldTo_Party_RagSoc { get; set; }
        public string SoldTo_Party_ind { get; set; }
        public string SoldTo_Party_CAP { get; set; }
        public string SoldTo_Party_loc { get; set; }
        public string SoldTo_Party_prov { get; set; }
        public string BillTo_Party_code { get; set; }
        public string BillTo_Party_RagSoc { get; set; }
        public string BillTo_Party_ind { get; set; }
        public string BillTo_Party_CAP { get; set; }
        public string BillTo_Party_loc { get; set; }
        public string BillTo_Party_prov { get; set; }
        public Nullable<int> NumImpianti { get; set; }
        public string Impianto_ind { get; set; }
        public string Impianto_CAP { get; set; }
        public string Impianto_loc { get; set; }
        public string StatusCorrente { get; set; }
        public string causale { get; set; }
        public string opportunity { get; set; }
        public string TipoEdificio_Traffico { get; set; }
        public string TipoEdificio_Segmento { get; set; }
        public string DurataContratto { get; set; }
        public string ServSupp { get; set; }
        public string Pagamento_Tipo { get; set; }
        public string Pagamento_modo { get; set; }
        public string Pagamento_Dilazione { get; set; }
        public Nullable<decimal> Canone_Offerto { get; set; }
        public Nullable<decimal> Canone_venduto { get; set; }
        public Nullable<decimal> Canone_Liv1 { get; set; }
        public Nullable<float> Sconto_offerto { get; set; }
        public Nullable<float> Sconto_venduto { get; set; }
        public string TipoContratto { get; set; }
        public Nullable<bool> AOC { get; set; }
        public Nullable<bool> PiRep { get; set; }
        public Nullable<bool> RipRep { get; set; }
        public Nullable<bool> KRMS { get; set; }
        public Nullable<bool> SIMCARD { get; set; }
        public Nullable<bool> EOPT { get; set; }
        public Nullable<System.DateTime> DataCreazione { get; set; }
    }
}
