//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRM_FAST
{
    using System;
    using System.Collections.Generic;
    
    public partial class TerminiDiPagamento
    {
        public string CodiceTerminiPagamento { get; set; }
        public string DescrizioneTerminiPagamento { get; set; }
        public string TestoTerminiPagamento { get; set; }
        public Nullable<float> Abbuono { get; set; }
    }
}
