//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRM_FAST
{
    using System;
    using System.Collections.Generic;
    
    public partial class Variabili
    {
        public int IDVariabili { get; set; }
        public string XPath { get; set; }
        public Nullable<int> IDConfiguratore { get; set; }
        public string NomeVariabile { get; set; }
        public string Quote { get; set; }
        public Nullable<bool> Rinominata { get; set; }
        public string NomeVecchio { get; set; }
    }
}
