//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRM_FAST
{
    using System;
    using System.Collections.Generic;
    
    public partial class VariabiliPrice
    {
        public int IDVariabiliPrice { get; set; }
        public int IDVariabili { get; set; }
        public int IDPrice { get; set; }
        public string Note { get; set; }
    }
}
