//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRM_FAST
{
    using System;
    using System.Collections.Generic;
    
    public partial class Venditori
    {
        public string KAI { get; set; }
        public string SALES_GROUP_CODE { get; set; }
        public string SALES_OFFICE_CODE { get; set; }
        public string Sigla { get; set; }
        public string KAIAmm { get; set; }
        public string KAIAmm2 { get; set; }
        public string KAICV { get; set; }
        public string KAISV { get; set; }
        public string CodiceSV { get; set; }
        public string KAISV2 { get; set; }
        public string CodiceSV2 { get; set; }
        public string KAICD { get; set; }
        public string KAIDIR { get; set; }
        public string FileFirma { get; set; }
        public string Telefono { get; set; }
        public string Fax { get; set; }
        public string Ufficio { get; set; }
        public string Indirizzo { get; set; }
        public string CAP { get; set; }
        public string Citta { get; set; }
        public Nullable<double> SogliaSconto { get; set; }
        public Nullable<double> SogliaValore { get; set; }
        public string persona { get; set; }
        public string email { get; set; }
        public string VisibilitaVenditori { get; set; }
        public string VisibilitaDistretti { get; set; }
        public string Cellulare { get; set; }
        public Nullable<int> ListinoClienti { get; set; }
        public short IsAdmin { get; set; }
        public short IsDSAM { get; set; }
        public Nullable<short> IsStandard { get; set; }
        public Nullable<short> IsMKT { get; set; }
        public short IsManager { get; set; }
        public short IsSupervisoreVB { get; set; }
        public short IsVenditore { get; set; }
        public short IsSupervisore { get; set; }
        public string Ruolo { get; set; }
        public short AbilitatoMTZElev { get; set; }
        public short AbilitatoMTZ { get; set; }
        public short AbilitatoDOOR { get; set; }
        public string SAP_OWNER { get; set; }
        public string KAISV_TRB { get; set; }
        public string KAISV_FRB { get; set; }
        public string KAISV_LAVORI { get; set; }
        public string KAIAMM_SEB { get; set; }
    }
}
